// This file is auto-generated by scripts/generate-registry.js
// Do not edit manually — changes will be overwritten.
export const registry = {

} as const;
export type IconId = keyof typeof registry;
